# Generated by Django 3.0.4 on 2021-05-09 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=6)),
                ('country', models.CharField(default='', max_length=40)),
                ('nativeLanguage', models.CharField(default='', max_length=40)),
                ('practisingLanguage', models.CharField(default='', max_length=40)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='default-profile-picture.jpg', upload_to='images')),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnreadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient2', to=settings.AUTH_USER_MODEL)),
                ('sender2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LatestSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minAge', models.IntegerField(default=0)),
                ('maxAge', models.IntegerField(default=100)),
                ('gender', models.CharField(default='Both', max_length=6)),
                ('country', models.CharField(default='All', max_length=40)),
                ('nativeLanguage', models.CharField(default='All', max_length=40)),
                ('practisingLanguage', models.CharField(default='All', max_length=40)),
                ('searcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LatestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('senders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
